### ISSUE TITLE
lsoie_wiki_train.json not found

### ISSUE THREAD

**Issue by SuoFei01** [daviddongkc/SMiLe_OIE#1]
Can you provide this dataset,pls.

**Comment by SuoFei01** [comment]
I would appreciate it if you could provide this dataset. My email is 719922485@qq.com

**Comment by banyedy** [comment]
Did you get the dataset? I also really need this part at the moment. Thank you very much.

**Comment by SuoFei01** [comment]
I'm sorry, I didn't get this dataset. The author said that he would upload github, but it hasn't been uploaded yet.


I'm sorry, I didn't get this dataset. The author said that he would upload github, but it hasn't been uploaded yet

suofei
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "daviddongkc/SMiLe_OIE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 下午3:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [daviddongkc/SMiLe_OIE] lsoie_wiki_train.json not found (Issue #1)





 
Did you get the dataset? I also really need this part at the moment. Thank you very much.

**Comment by daviddongkc** [comment]
The conversion file is uploaded for your information.
