### ISSUE TITLE
Sorry to add an issue here

### ISSUE THREAD

**Issue by Violettttee** [daviddongkc/SMiLe_OIE#4]
recently i'm reading your and your team's paper 'Shall We Trust All Relational Tuples by Open Information Extraction?A Study on Speculation Detection'.I clicked the link on https://www.catalyzex.com/paper/arxiv:2305.04181/code but couldn't find your code attached .It will be appreciated if it is convenient for you to share it again.

**Comment by daviddongkc** [comment]
hi, the code requested can be found at https://github.com/daviddongkc/OIE_Spec.

**Comment by daviddongkc** [comment]
hi, the code requested can be found at https://github.com/daviddongkc/OIE_Spec.
